site_name: EvalSense Documentation
site_description: A tool for systematic large language model evaluation.
repo_url: https://github.com/nhsengland/evalsense
repo_name: nhsengland/evalsense
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            separate_signature: true
            inherited_members: true
            show_signature_annotations: true
            summary: true
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - Home: index.md
  - API Reference:
      - Datasets:
        - datasets: api-reference/datasets/base.md
        - datasets.managers: api-reference/datasets/managers.md
      - Evaluation:
        - evaluation: api-reference/evaluation/base.md
        - evaluation.evaluators: api-reference/evaluation/evaluators.md
      - Generation:
        - generation: api-reference/generation/base.md
      - Tasks:
        - tasks: api-reference/tasks/base.md
      - Utils:
        - utils: api-reference/utils/base.md
      - Workflow:
        - workflow: api-reference/workflow/base.md
        - workflow.analysers: api-reference/workflow/analysers.md
  - "EvalSense Homepage": https://nhsengland.github.io/evalsense/
