site_name: LLMScope Documentation
site_description: A tool for evaluating LLM performance on healthcare tasks.
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            separate_signature: true
            inherited_members: true
            show_signature_annotations: true
            summary: true
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - Home: index.md
  - API Reference:
      - Datasets:
        - datasets: api-reference/datasets/base.md
        - datasets.managers: api-reference/datasets/managers.md
      - LLMs:
        - llms: api-reference/LLMs/base.md
        - llms.managers: api-reference/LLMs/managers.md
      - Pipelines:
        - pipelines: api-reference/pipelines/base.md
      - Prompts:
        - prompts: api-reference/prompts/base.md
      - Tasks:
        - tasks: api-reference/tasks/base.md
      - Utils:
        - utils: api-reference/utils/base.md
