name: Deploy GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Install Docusaurus project
        working-directory: guide
        run: npm ci
      - name: Build Docusaurus project
        working-directory: guide
        run: npm run build
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: 0.7.3
          activate-environment: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - name: Install Python project development dependencies
        run: uv sync --only-dev
      - name: Verify target MkDocs directory
        run: |
          if [ -d "guide/build/docs" ]; then
            echo "The directory guide/build/docs already exists. Aborting."
            exit 1
          fi
      - name: Build MkDocs
        run: mkdocs build --site-dir guide/build/docs
      - name: Disable Jekyll
        run: touch guide/build/.nojekyll
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: guide/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
